# config file containing parameters
configfile: "config/config.yml"

include: "rules/simulate_guide_assignments.smk"
include: "rules/run_power_analysis.smk"

# perform all differential expression and power analyses to create main output files
rule all:
  input:
    expand("results/{sample}/power_analysis_plots.html", sample=config['samples'])

